import movieOne from "../images/movies/1.jpg";
import movieTwo from "../images/movies/2.jpg";
import movieThree from "../images/movies/3.jpg";
import movieFour from "../images/movies/4.jpg";
import movieFive from "../images/movies/5.jpg";
import movieSix from "../images/movies/6.jpg";
import movieSeven from "../images/movies/7.jpg";
import movieEight from "../images/movies/8.jpg";
import movieNine from "../images/movies/9.jpg";
import movieTen from "../images/movies/10.jpg";
import movieEleven from "../images/movies/11.jpg";
import movieTwelve from "../images/movies/12.jpg";

const moviesList = [
  {
    country: "",
    director: "",
    duration: 107,
    year: "",
    description: "",
    image: movieOne,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 1,
    nameRU: "33 слова о дизайне",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 107,
    year: "",
    description: "",
    image: movieTwo,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 2,
    nameRU: "Киноальманах «100 лет дизайна»",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 58,
    year: "",
    description: "",
    image: movieThree,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 3,
    nameRU: "В погоне за Бенкси",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 131,
    year: "",
    description: "",
    image: movieFour,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 4,
    nameRU: "Баския: Взрыв реальности",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 82,
    year: "",
    description: "",
    image: movieFive,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 5,
    nameRU: "Бег это свобода",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 15,
    year: "",
    description: "",
    image: movieSix,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 6,
    nameRU: "Книготорговцы",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 102,
    year: "",
    description: "",
    image: movieSeven,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 7,
    nameRU: "Когда я думаю о Германии ночью",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 46,
    year: "",
    description: "",
    image: movieEight,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 8,
    nameRU: "Gimme Danger: История Игги и The Stooges",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 69,
    year: "",
    description: "",
    image: movieNine,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 9,
    nameRU: "Дженис: Маленькая девочка грустит",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 83,
    year: "",
    description: "",
    image: movieTen,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 10,
    nameRU: "Соберись перед прыжком",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 115,
    year: "",
    description: "",
    image: movieEleven,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 11,
    nameRU: "Пи Джей Харви: A dog called money",
    nameEN: "",
  },
  {
    country: "",
    director: "",
    duration: 123,
    year: "",
    description: "",
    image: movieTwelve,
    trailerLink: "",
    thumbnail: "",
    owner: "",
    movieId: 12,
    nameRU: "По волнам: Искусство звука в кино",
    nameEN: "",
  },
];

export default moviesList;
